### ISSUE TITLE
Backtracking in one_ore_more_separated

### ISSUE THREAD

**Issue by SunghoLee** [hbr/fmlib#2]
Hi,

I think that the `one_ore_more_separated` parser combinator needs to support backtracking for the combined parser of `sep` and `item`. The current implementation is the follow:
```
    let one_or_more_separated
            (first: 'item -> 'r)
            (next:  'r -> 'sep  -> 'item -> 'r)
            (p: 'item t)
            (sep: 'sep t)
        : 'r t
        =
        let rec many r =
            (
                let* s    = sep in
                let* item = p in
                many (next r s item))
                </>
                return r
            in
            let* item = p in
            many (first item)
```
Let's assume that the `sep` parser succeeds in parsing a separator token but the `p` fails in parsing the next token. Then, the current implementation fails in parsing with consuming the separator token. Thus, the `one_or_more_separated` parser combinator never retuns `r`, because of the semantics of the `</>` combinator. The current implementation only work well for that case that the parser fails in parsing a separator token. It is a quite inconvenient and I cannot find any workarounds for it without changing the parser combinator. 

Does it make sense? Or, is it better for users to implement and use another version of the combinator supporting backtracking for such case, because the behavior is intentional?

**Comment by hbr** [comment]
Good point. `one_or_more_separated` is a convenience combinator and not a basic combinator. I have designed it in a way which I think most people would expect it to work.

In principle it is easy to make a new combinator which makes the combination of the separator and the item backtrackable.

    let one_or_more_separated2
            (first: 'item -> 'r)
            (next:  'r -> 'sep  -> 'item -> 'r)
            (p: 'item t)
            (sep: 'sep t)
        : 'r t
        =
        let pair =
            let* s = sep in
            let* item = p in
            return (s,p)
        in
        let rec many r =
            (
                let* s,item = backtrack pair in
                many (next r s item)
             )
             </>
             return r
        in
        let* item = p in
        many (first item)

The question: Is this a good idea? I have the following comments:

1. I try to avoid backtracking if possible. Any backtracking combinator makes the whole parser less efficient, because it requires buffering of the token and replaying of the buffered token in case the combinator fails. However in some cases backtracking is unavoidable.

2. If a sequence of one more separated items have to be parsed, the presence of the separator usually means that at least one more item is expected. If the item parser fails, the parser fails exactly at the position where the user expects it to fail -- namely at the start or within the wrong item. Usual separators are commas or semicolons. E.g. lists have the form `[a, b, c, d]` or `[a; b; c; d]`.

3. If the separator is a terminator and not a separator, then it is better to use `one_or_more` or `zero_or_more` and make the item parser as a combinator which parses the item followed by the (optional) terminator.

4. I don't know which grammatical construct you have in mind, if you want to fail the combination of the separator and the next item at the start of the separator. This might confuse your users. The error message points to the beginning of the separator because the parser cannot successfully parse the next item and therefore backtracks. However the user looks at the separator and thinks the separator is perfect and asks: "Why is the parser complaining here?".

Could you explain the structure you want to parse to understand your needs better.

Regards
Helmut

**Comment by SunghoLee** [comment]
Sorry for the late response.

The code you wrote in this issue completely works well and I also used my own version of `one_or_more_separated` similar to it to avoid the issue. 

The background is that I try to implement a Python parser using fmlib_parse, and the Python syntax is formally described in PEG grammar.  In PEG, `','.something+` means the one or more separated as the same to the `one_or_more_separated` function. Thus, I want to use the function directly to parse that kinds of things. But, in the Python grammar, there are some cases that parsing a separator succeeds but parsing a item fails like the follow: 
```
kwargs:
  | ','.kwarg_or_starred+ ',' ','.kwarg_or_double_starred+
  | ','.kwarg_or_starred+
  | ','.kwarg_or_double_starred+
```
In the example, `kwarg_or_starred` is one or more separated by a comma, but also followed by comma and one or more separated `kwarg_or_double_starred`. Thus, the current implementation of `one_or_more_separated` just fails with consumed the comma token. 

It is Okay to keep the current implementation since it is easy to implement new version of `one_or_more_separated`. However, because it works in a way that I didn't expected, I was not able to find the cause of the parsing failure before checking the implementation. 

How about describe such behavior in the documentation for users to understand it correctly?

**Comment by hbr** [comment]
Could you give some specific examples of the construct `kwargs`. I have the suspicion that a combinator which parses a comma separated list of `kwarg_or_starred` or `kwarg_or_double_starred` would be much more efficient and wrong sequence of starred or double starred items could be sorted out as a semantic error.

**Comment by SunghoLee** [comment]
More concrete example is that `kwarg_or_starred` can be either `id = expression` or `'*' expression`, and `kwarg_or_double_starred` can be either `id = expression` or `'**' expression`. I know that the grammar is not elegant (there are many optimization points), but I want to use the grammar directly without modification for further maintenance.
