### ISSUE TITLE
Usecases of indentation parsing

### ISSUE THREAD

**Issue by SunghoLee** [hbr/fmlib#3]
Sorry for opening multiple issues at once.

I try to use the indentation parsing feature, but there are no sufficient materials for me to know how to use it. Could you give me some example parsers with their target strings?

**Comment by hbr** [comment]
In the unit test module `test_character.ml` there are some success and failure examples for indentation sensitive parsing. https://github.com/hbr/fmlib/blob/master/src/parse/test_character.ml.

In the documentation https://hbr.github.io/fmlib/odoc/fmlib_parse you find some general description.

I case this is not sufficient let me know. I am prepared to improve the documentation because I think that indentation sensitive parsing is one of the most important features of the parsing library.

**Comment by SunghoLee** [comment]
Thank you for sharing, and I agree that the usability of indentation sensitive parsing. 
After looking into the tests in detail, I would get in touch with you if there are some points that I cannot understand. 

Close this issue.
