### ISSUE TITLE
Caching parsing results

### ISSUE THREAD

**Issue by SunghoLee** [hbr/fmlib#4]
Hi,

Is there a way to cache parsing results of a parser and reuse them when getting the same inputs? 

A parser can try to parse the same inputs lots of times w.r.t a grammar that is not well-defined. Even though the best solution is to change the grammar to prevent parsers from doing that, sometimes caching might be a good solution as well to avoid performance overhead in that case.

**Comment by SunghoLee** [comment]
I didn't be aware of the importance uses of `Fmlib_parse` in IDEs. Thanks.

Is there an API via which parsers get the current input buffer index? Because I'm not targeting the case like IDEs, the API enables me to implement a memoization parser combinator only for my case. 

I'm wondering how much performance such preprocessings (e.g. Lexing) can improve. The root cause of the performance degradation is that parsers repeat to parse same inputs again and again. I think that the preprocessings would be efficient only for parsers for "tokenization", but would not for the other parsers that parse more complex structures. I already have a lexer for the Python, so I will also try Lexing first and Parsing on tokens, and check how much the performance is improved.

**Comment by hbr** [comment]
1. There is no API to get the current input buffer index. But parsers can have a user state and there are combinators to access the user state. If you parse some part of the input successfully, you can put the result into the user state. Backtracking resets the user state to the state at the start of the substructure. If the state is immutable you can not memorize the result. However if you have in the state a pointer to a mutable structure which stores the result, you have access to it. But you have to be careful.

2. Tokenizing improves the efficiency of backtracking considerably because in the lexer a token is a character and in the high level parser a token is a token. Backtracking in the high level parser just replays one or two token, backtracking in a character parser replays all characters (including whitespace).

**Comment by hbr** [comment]
I close this issue. If there are new aspects especially on tokenizing, please feel free to open a new issue.
